# nginx - main.yml

- name: Copy nginx Dockerfile and files on host
  ansible.builtin.copy:
    src: .
    dest: "{{ nginx_docker_context_path }}/"
- name: Build nginx Docker image
  community.docker.docker_image:
    name: "{{ nginx_docker_image_name }}"
    tag: "{{ nginx_docker_image_tag }}"
    build:
      path: "{{ nginx_docker_context_path }}/"
    source: build
    state: present
    force_source: yes
