# nginx - main.yml

- name: Copy nginx Dockerfile and files on host
  ansible.builtin.copy:
    src: .
    dest: /etc/docker/cloud1/nginx/
  become: yes
  tags:
    - build
    - nginx
- name: Build nginx Docker image
  community.docker.docker_image:
    name: ft_nginx
    tag: latest
    build:
      path: /etc/docker/cloud1/nginx/
    source: build
    state: present
    force_source: yes
  become: yes
  tags:
    - build
    - nginx
