---
# defaults file for phpmyadmin

# Docker context path
phpmyadmin_docker_context_path: /etc/docker/ft_phpmyadmin
# Container name
phpmyadmin_docker_ctn_name: phpmyadmin
# Image name
phpmyadmin_docker_image_name: ft_phpmyadmin
# Image tag
phpmyadmin_docker_image_tag: latest
# "Retain anonymous volumes associated with a removed container"
phpmyadmin_docker_keep_volumes: no
# Docker network(s) in which the container will be added
phpmyadmin_docker_networks:
  - { name: bridge }
# Path of phpmyadmin files
phpmyadmin_docker_site_path: /usr/share/nginx/phpmyadmin
# Volumes used with phpmyadmin container
phpmyadmin_docker_volumes:
  - "{{ phpmyadmin_docker_ctn_name }}:{{ phpmyadmin_docker_site_path }}"
  - "{{ phpmyadmin_docker_context_path }}/config.inc.php:{{ phpmyadmin_docker_site_path }}/config.inc.php"
# Restart policy for the container
phpmyadmin_docker_restart_policy: unless-stopped
# Host on which the DB is hosted
phpmyadmin_docker_db_host: ''
phpmyadmin_docker_fastcgi_pass: "localhost:9000"
