---
# defaults file for mysql

# Docker path to context
mysql_docker_context_path: /etc/docker/cloud1/ft_mysql/
# Container name
mysql_docker_ctn_name: db
# Image name
mysql_docker_image_name: ft_mysql
# Image tag
mysql_docker_image_tag: latest
# "Retain anonymous volumes associated with a removed container"
mysql_docker_keep_volumes: no
# Docker network in which the container will be added
mysql_docker_network: bridge
# Database root password
mysql_docker_root_password: root
# Volumes used with mysql container
mysql_docker_volumes:
  - mysql:/var/lib/mysql
# Restart policy for the container
restart_policy: unless-stopped
