services:
  reverse-proxy:
    image: "ft_nginx"
    ports:
      - "80:80"
    volumes:
      - "./docker/reverse-proxy/wordpress.conf:/etc/nginx/conf.d/wordpress.conf"
      - "./docker/reverse-proxy/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf"
    depends_on:
      - phpmyadmin
      - wordpress
  wordpress:
    build: "docker/wordpress"
    volumes:
      - wordpress:/usr/share/nginx/wordpress
    depends_on:
      - php-fpm
  phpmyadmin:
    build: "docker/phpmyadmin"
    volumes:
      - phpmyadmin:/usr/share/nginx/phpmyadmin
    depends_on:
      - php-fpm
  php-fpm:
    build: "docker/php-fpm"
    volumes:
      - wordpress:/usr/share/nginx/wordpress
      - phpmyadmin:/usr/share/nginx/phpmyadmin
  db:
    build: "docker/mysql"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  wordpress:
  phpmyadmin:
  mysql:
