all:
  children:
    prod:
      children:
        aws:
          hosts:
            aws1:
    dev:
      children:
        vagrant:
          hosts:
            alpine:
              ansible_port: 4345
            debian:
              ansible_port: 3345
            fedora:
              ansible_port: 2345
            ubuntu:
              ansible_port: 1345
          vars:
            ansible_user: vagrant
            ansible_host: 127.0.0.1
            ansible_ssh_private_key_file: .vagrant/machines/cloud1-{{ inventory_hostname }}/virtualbox/private_key
