---
# Cloud-1 - install.yml

- name: Install Cloud-1
  hosts: all
  vars:
    docker_networks_list:
      - cloud-1
  become: yes
  roles:
    - name: import docker role
      role: docker
      tags:
        - docker
    - name: import mysql role
      role: mysql
      tags:
        - mysql
    - name: import nginx role
      role: nginx
      tags:
        - nginx
    - name: import phpmyadin role
      role: phpmyadmin
      tags:
        - phpmyadmin
    - name: import wordpress role
      role: wordpress
      tags:
        - wordpress
    - name: import php-fpm role
      role: php-fpm
      tags:
        - php-fpm
  tasks:
    - name: Create Docker network
      ansible.builtin.import_tasks: roles/docker/tasks/network.yml
      become: yes
    - name: Create mysql container
      ansible.builtin.import_tasks: roles/mysql/tasks/run.yml
      vars:
        - docker_network_name: "{{ docker_networks_list[0] }}"
      tags:
        - mysql
