---
# Cloud-1 - install.yml

- name: Install Cloud-1
  hosts: all
  roles:
    - role: docker
      tags:
        - docker
      become: yes
    - role: mysql
      tags:
        - mysql
    - role: nginx
      tags:
        - nginx
    - role: phpmyadmin
      tags:
        - phpmyadmin
    - role: wordpress
      tags:
        - wordpress
    - role: php-fpm
      tags:
        - php-fpm
