---
# Cloud-1 - install.yml

- name: Install Cloud-1
  hosts: all
  vars:
    docker_networks_list:
      - { name: cloud-1 }
  become: yes
  roles:
    - name: import docker role
      role: docker
      tags:
        - docker
    - name: import mysql role
      role: mysql
      tags:
        - mysql
      vars:
        mysql_docker_networks:
          - "{{ docker_networks_list[0] }}"
