# handlers file for reverse_proxy 
- name: Restart reverse proxy container
  community.docker.docker_container:
    name: "{{ reverseproxy_docker_ctn_name }}"
    image: "{{ reverseproxy_docker_image_name }}"
    state: started
    restart: yes
    container_default_behavior: no_defaults
    detach: yes
    keep_volumes: no
    networks: "{{ reverseproxy_docker_networks }}"
    network_mode: default
    published_ports: "{{ reverseproxy_docker_published_ports }}"
    restart_policy: "{{ reverseproxy_docker_restart_policy }}"
    volumes: "{{ reverseproxy_docker_volumes }}"
  when: reverseproxy_fresh_run.changed is false or reverseproxy_generate_certificate is true
