# php_fpm - main.yml

- name: Copy php-fpm Dockerfile
  ansible.builtin.copy:
    src: .
    dest: "{{ phpfpm_docker_context_path }}/"
- name: Build php-fpm Docker image
  community.docker.docker_image:
    name: "{{ phpfpm_docker_image_name }}"
    tag: "{{ phpfpm_docker_image_tag }}"
    build:
      path: "{{ phpfpm_docker_context_path }}/"
    source: build
    state: present
    force_source: yes
