# wordpress - main.yml

- name: Copy wordpress files on host
  ansible.builtin.copy:
    src: .
    dest: "{{ wordpress_docker_context_path }}/"
- name: Copy wordpress Dockerfile
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ wordpress_docker_context_path }}/{{ item }}"
  loop:
    - Dockerfile
    - wordpress.conf
- name: Build wordpress Docker image
  community.docker.docker_image:
    name: "{{ wordpress_docker_image_name }}"
    tag: "{{ wordpress_docker_image_tag }}"
    build:
      path: "{{ wordpress_docker_context_path }}/"
    source: build
    state: present
    force_source: yes
