# wordpress - main.yml

- name: Copy wordpress files on host
  ansible.builtin.copy:
    src: .
    dest: "{{ wordpress_docker_context_path }}/"
- name: Generate wordpress files on host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ wordpress_docker_context_path }}/{{ item }}"
  loop:
    - Dockerfile
    - wordpress.conf
    - wp-config.php
- name: Build wordpress Docker image
  community.docker.docker_image:
    name: "{{ wordpress_docker_image_name }}"
    tag: "{{ wordpress_docker_image_tag }}"
    build:
      path: "{{ wordpress_docker_context_path }}/"
    source: build
    state: present
    force_source: yes
- name: Run wordpress Docker container
  community.docker.docker_container:
    name: "{{ wordpress_docker_ctn_name }}"
    image: "{{ wordpress_docker_image_name }}"
    state: started
    container_default_behavior: no_defaults
    detach: yes
    keep_volumes: no
    networks: "{{ wordpress_docker_networks }}"
    restart_policy: "{{ wordpress_docker_restart_policy }}"
    volumes: "{{ wordpress_docker_volumes }}"
    network_mode: default
