# ft_wordpress

# use ft_wordpress as base image
FROM ft_nginx:latest

# update and upgrade packages
RUN apk update\
  && apk upgrade
# copy and extract wordpresssources to the container
ADD wordpress-latest.tar.gz "{{ wordpress_docker_site_path }}"

# copy nginx configuration file for wordpress
COPY wordpress.conf /etc/nginx/conf.d/

# remove default site and its associate nginx config file
RUN rm -rf /usr/share/nginx/html\
  && rm /etc/nginx/conf.d/default.conf
