# phpmyadmin - main.yml

#
# Create a phpmyadmin Docker image
# based on the ft_nginx image
#

- name: Copy phpmyadmin files on host
  ansible.builtin.copy:
    src: .
    dest: "{{ phpmyadmin_docker_context_path }}/"
- name: Copy phpmyadmin Dockerfile on host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ phpmyadmin_docker_context_path }}/{{ item }}"
  vars:
    blowfish_secret: "{{ lookup('password', '/dev/null length=32') }}"
  loop:
    - Dockerfile
    - phpmyadmin.conf
    - config.inc.php
- name: Build phpmyadmin Docker image
  community.docker.docker_image:
    name: "{{ phpmyadmin_docker_image_name }}"
    tag: "{{ phpmyadmin_docker_image_tag }}"
    build:
      path: "{{ phpmyadmin_docker_context_path }}/"
    source: build
    state: present
    force_source: yes
- name: Run phpmyadmin Docker container
  community.docker.docker_container:
    name: "{{ phpmyadmin_docker_ctn_name }}"
    image: "{{ phpmyadmin_docker_image_name }}"
    state: started
    container_default_behavior: no_defaults
    detach: yes
    keep_volumes: no
    networks: "{{ phpmyadmin_docker_networks }}"
    network_mode: default
    purge_networks: yes
    restart_policy: "{{ phpmyadmin_docker_restart_policy }}"
    volumes: "{{ phpmyadmin_docker_volumes }}"
