# phpmyadmin - main.yml

- name: Copy phpmyadmin Dockerfile and files on host
  ansible.builtin.copy:
    src: .
    dest: /etc/docker/cloud1/phpmyadmin/
  become: yes
  tags:
    - build
    - phpmyadmin
- name: Build phpmyadmin Docker image
  community.docker.docker_image:
    name: ft_phpmyadmin
    tag: latest
    build:
      path: /etc/docker/cloud1/phpmyadmin/
    source: build
    state: present
  become: yes
  tags:
    - build
    - phpmyadmin
