# mysql - main.yml

- name: Copy mysql Dockerfile and files on host
  ansible.builtin.copy:
    src: .
    dest: /etc/docker/cloud1/mysql/
  become: yes
  tags:
    - build
    - mysql
- name: Build MySQL Docker image
  community.docker.docker_image:
    name: ft_mysql
    tag: latest
    build:
      path: /etc/docker/cloud1/mysql/
    source: build
    state: present
  become: yes
  tags:
    - build
    - mysql
