# mysql - main.yml

- name: Copy mysql key on host
  ansible.builtin.copy:
    src: mysql.key
    dest: /etc/docker/cloud1/mysql/
  become: yes
  tags:
    - build
    - mysql
- name: Copy mysql Dockerfile on host
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: /etc/docker/cloud1/mysql/Dockerfile
  become: yes
  tags:
    - build
    - mysql
- name: Build MySQL Docker image
  community.docker.docker_image:
    name: ft_mysql
    tag: latest
    build:
      path: /etc/docker/cloud1/mysql/
    source: build
    state: present
    force_source: yes
  become: yes
  tags:
    - build
    - mysql
