# mysql - main.yml

- name: Copy mysql key on host
  ansible.builtin.copy:
    src: mysql.key
    dest: "{{ docker_mysql_context_path }}"
  tags:
    - build
    - mysql
- name: Copy mysql Dockerfile on host
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ docker_mysql_context_path }}"
  tags:
    - build
    - mysql
- name: Build MySQL Docker image
  community.docker.docker_image:
    name: "{{ docker_mysql_image_name }}"
    tag: "{{ docker_mysql_image_tag }}"
    build:
      path: "{{ docker_mysql_context_path }}"
    source: build
    state: present
    force_source: yes
  tags:
    - build
    - mysql
