# upgrade - main.yml

#
# Upgrade system packages
# 

- name: upgrade packages on debian-based system
  ansible.builtin.import_tasks: debian_based.yml
  when: ansible_facts['os_family'] | lower == 'debian'
- name: upgrade packages on rhel-based system using dnf package manager
  ansible.builtin.import_tasks: rhel_based_dnf.yml
  when:
    - ansible_facts['os_family'] | lower == 'redhat'
    - ansible_facts['pkg_mgr'] | lower == 'dnf'
- name: upgrade packages on arch-based system
  ansible.builtin.import_tasks: arch_based.yml
  when: ansible_facts['os_family'] | lower == 'archlinux'
