# handlers file for wordpress
- name: Restart wordpress Docker container
  community.docker.docker_container:
    name: "{{ wordpress_docker_ctn_name }}"
    image: "{{ wordpress_docker_image_name }}"
    state: started
    container_default_behavior: no_defaults
    detach: yes
    keep_volumes: no
    networks: "{{ wordpress_docker_networks }}"
    network_mode: default
    purge_networks: yes
    restart_policy: "{{ wordpress_docker_restart_policy }}"
    volumes: "{{ wordpress_docker_volumes }}"
    restart: yes
  when: wordpress_fresh_run.changed == false
    or wordpress_config_update.changed == true
