# phpmyadmin

# use ft_nginx as base image
FROM ft_nginx:latest

# update and upgrade packages
RUN apk update\
  && apk upgrade

# copy and extract phpmyadmin sources to the container
ADD phpmyadmin.tar.gz /tmp/

RUN mkdir -p $(dirname "{{ phpmyadmin_docker_site_path }}")\
  && mv /tmp/phpMyAdmin-5.1.1-all-languages "{{ phpmyadmin_docker_site_path }}"

# copy nginx configuration file for phpmyadmin
COPY phpmyadmin.conf /etc/nginx/conf.d/

# remove default site and its associate nginx config file
RUN rm -rf /usr/share/nginx/html\
  && rm /etc/nginx/conf.d/default.conf
