---
# defaults file for reverse_proxy

# Container name
reverseproxy_docker_ctn_name: proxy
# Image to use to for container
reverseproxy_docker_image_name: "{{ nginx_docker_image_name }}"
# Docker network(s) in which the container will be added
reverseproxy_docker_networks:
  - { name: bridge }
# List of ports to be published
reverseproxy_docker_published_ports:
  - "80:80"
  - "443:443"
reverseproxy_docker_restart_policy: unless-stopped
reverseproxy_docker_context_path: "/etc/docker/proxy"
reverseproxy_docker_volumes:
  - "{{ reverseproxy_docker_context_path }}/conf.d/:/etc/nginx/conf.d/"
  - "{{ reverseproxy_docker_context_path }}/nginx.conf:/etc/nginx/nginx.conf"
  - "{{ reverseproxy_docker_context_path }}/certs/:/root/certs"
