# Docker - arch_based.yml

#
# Install Docker on a Arch-based system
#

- name: arch-based - Install Docker Engine
  community.general.pacman:
    name:
      - docker
    state: present
    update_cache: yes
  become: yes

# Install Python Package Installer required for
# Docker SDK for Python installation
- name: arch-based - Install Python package installer
  community.general.pacman:
    name:
      - python-pip
    state: present
    update_cache: yes
  become: yes
  tags:
    - python
