# Docker - arch_based.yml
#
# Install Docker on a Arch-based system
#

- name: Install Docker Engine
  community.general.pacman:
    name:
      - docker
    state: present
    update_cache: yes
  become: yes

# Install Ansible requirements to control Docker
- name: Install Python package installer
  community.general.pacman:
    name:
      - python-pip
    state: present
    update_cache: yes
  become: yes
  tags:
    - python
