# Docker - debian_based.yml

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes
- name: Import Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"
    state: present
  become: yes
- name: Add Docker stable repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] }} stable"
    filename: "docker"
    update_cache: yes
    state: present
  become: yes
- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: present
    update_cache: yes
  become: yes

# Install Ansible requirements to control Docker
- name: Install Python package installer
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
    update_cache: yes
  become: yes
  tags:
    - python
