# Docker - main.yml

# debian based hosts
- name: Install Docker on Debian based hosts
  ansible.builtin.import_tasks: debian_based.yml
  when: ansible_facts['os_family'] | lower == 'debian'
# Arch based hosts
- name: Install Docker on Arch based hosts
  ansible.builtin.import_tasks: arch_based.yml
  when: ansible_facts['os_family'] | lower == 'archlinux'
