# Docker - main.yml
#
# These tasks install Docker and enable Docker service.
# They also install the Docker SDK for Python required by
# the community.docker module to control Docker.
#

# Install Docker on host
## debian based hosts
- name: Install Docker on Debian based hosts
  ansible.builtin.import_tasks: debian_based.yml
  when: ansible_facts['os_family'] | lower == 'debian'
## Arch based hosts
- name: Install Docker on Arch based hosts
  ansible.builtin.import_tasks: arch_based.yml
  when: ansible_facts['os_family'] | lower == 'archlinux'
## RHEL based hosts
- name: Install Docker on RHEL based hosts using dnf package manager
  ansible.builtin.import_tasks: rhel_based_dnf.yml
  when:
    - ansible_facts['os_family'] | lower == 'redhat'
    - ansible_facts['pkg_mgr'] | lower == 'dnf'

# Install Docker SDK for Python
- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name:
      - docker
    state: present
  become: yes
  tags:
    - python

# Enable and start Docker service
- name: Enable Docker service
  ansible.builtin.import_tasks: start.yml
