# Docker - network.yml

#
# Creation of one or more Docker networks
#

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ item.name }}"
    state: present
  loop: "{{ docker_networks_list }}"
