# Docker - start.yml

# Enable and start Docker service on System D
- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
  when: ansible_facts['service_mgr'] | lower == 'systemd'
